# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 779fc8ddaab1a07588f4824ec85bf7f462d5e0d55bd5d809c225d58723cff869cbbc2d0234d8555866c2f68d9d453e70e16f41d4445647e31f4db82af2e86fe7

test:
  secret_key_base: ac45d7cf40983468b120abc00a5f23f153fcd1a9ca73af34fae633952e5d9af265c4e7d6838ebbcf2501d94b7dfa16f02fe571647db8ab0696ad782245fb0842

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
